# Generated by Django 2.1.4 on 2019-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(max_length=100)),
                ('apihash', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13)),
            ],
        ),
    ]
